// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: app_image_search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	UseCache      bool                   `protobuf:"varint,3,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_app_image_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Similarity    float64                `protobuf:"fixed64,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
	ProductUrl    string                 `protobuf:"bytes,5,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	CategoryUrl   string                 `protobuf:"bytes,6,opt,name=category_url,json=categoryUrl,proto3" json:"category_url,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_app_image_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SearchResult) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *SearchResult) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SearchResult) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResult) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *SearchResult) GetCategoryUrl() string {
	if x != nil {
		return x.CategoryUrl
	}
	return ""
}

func (x *SearchResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ProcessingTime struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EmbeddingSeconds float64                `protobuf:"fixed64,1,opt,name=embedding_seconds,json=embeddingSeconds,proto3" json:"embedding_seconds,omitempty"`
	SearchSeconds    float64                `protobuf:"fixed64,2,opt,name=search_seconds,json=searchSeconds,proto3" json:"search_seconds,omitempty"`
	TotalSeconds     float64                `protobuf:"fixed64,3,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessingTime) Reset() {
	*x = ProcessingTime{}
	mi := &file_app_image_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingTime) ProtoMessage() {}

func (x *ProcessingTime) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingTime.ProtoReflect.Descriptor instead.
func (*ProcessingTime) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingTime) GetEmbeddingSeconds() float64 {
	if x != nil {
		return x.EmbeddingSeconds
	}
	return 0
}

func (x *ProcessingTime) GetSearchSeconds() float64 {
	if x != nil {
		return x.SearchSeconds
	}
	return 0
}

func (x *ProcessingTime) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

type SearchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results        []*SearchResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ProcessingTime *ProcessingTime        `protobuf:"bytes,4,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Device         string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	Cached         bool                   `protobuf:"varint,6,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_app_image_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchResponse) GetProcessingTime() *ProcessingTime {
	if x != nil {
		return x.ProcessingTime
	}
	return nil
}

func (x *SearchResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SearchResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_app_image_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_app_image_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_image_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_app_image_search_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_app_image_search_proto protoreflect.FileDescriptor

const file_app_image_search_proto_rawDesc = "" +
	"\n" +
	"\x16app_image_search.proto\x12\fimage_search\"`\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x1b\n" +
	"\tuse_cache\x18\x03 \x01(\bR\buseCache\"\xeb\x01\n" +
	"\fSearchResult\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x01R\n" +
	"similarity\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x01R\bdistance\x12\x1f\n" +
	"\vproduct_url\x18\x05 \x01(\tR\n" +
	"productUrl\x12!\n" +
	"\fcategory_url\x18\x06 \x01(\tR\vcategoryUrl\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"\x89\x01\n" +
	"\x0eProcessingTime\x12+\n" +
	"\x11embedding_seconds\x18\x01 \x01(\x01R\x10embeddingSeconds\x12%\n" +
	"\x0esearch_seconds\x18\x02 \x01(\x01R\rsearchSeconds\x12#\n" +
	"\rtotal_seconds\x18\x03 \x01(\x01R\ftotalSeconds\"\xed\x01\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.image_search.SearchResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12E\n" +
	"\x0fprocessing_time\x18\x04 \x01(\v2\x1c.image_search.ProcessingTimeR\x0eprocessingTime\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12\x16\n" +
	"\x06cached\x18\x06 \x01(\bR\x06cached\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xb2\x01\n" +
	"\x12ImageSearchService\x12H\n" +
	"\vSearchImage\x12\x1b.image_search.SearchRequest\x1a\x1c.image_search.SearchResponse\x12R\n" +
	"\vHealthCheck\x12 .image_search.HealthCheckRequest\x1a!.image_search.HealthCheckResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_app_image_search_proto_rawDescOnce sync.Once
	file_app_image_search_proto_rawDescData []byte
)

func file_app_image_search_proto_rawDescGZIP() []byte {
	file_app_image_search_proto_rawDescOnce.Do(func() {
		file_app_image_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_image_search_proto_rawDesc), len(file_app_image_search_proto_rawDesc)))
	})
	return file_app_image_search_proto_rawDescData
}

var file_app_image_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_image_search_proto_goTypes = []any{
	(*SearchRequest)(nil),       // 0: image_search.SearchRequest
	(*SearchResult)(nil),        // 1: image_search.SearchResult
	(*ProcessingTime)(nil),      // 2: image_search.ProcessingTime
	(*SearchResponse)(nil),      // 3: image_search.SearchResponse
	(*HealthCheckRequest)(nil),  // 4: image_search.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: image_search.HealthCheckResponse
}
var file_app_image_search_proto_depIdxs = []int32{
	1, // 0: image_search.SearchResponse.results:type_name -> image_search.SearchResult
	2, // 1: image_search.SearchResponse.processing_time:type_name -> image_search.ProcessingTime
	0, // 2: image_search.ImageSearchService.SearchImage:input_type -> image_search.SearchRequest
	4, // 3: image_search.ImageSearchService.HealthCheck:input_type -> image_search.HealthCheckRequest
	3, // 4: image_search.ImageSearchService.SearchImage:output_type -> image_search.SearchResponse
	5, // 5: image_search.ImageSearchService.HealthCheck:output_type -> image_search.HealthCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_image_search_proto_init() }
func file_app_image_search_proto_init() {
	if File_app_image_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_image_search_proto_rawDesc), len(file_app_image_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_image_search_proto_goTypes,
		DependencyIndexes: file_app_image_search_proto_depIdxs,
		MessageInfos:      file_app_image_search_proto_msgTypes,
	}.Build()
	File_app_image_search_proto = out.File
	file_app_image_search_proto_goTypes = nil
	file_app_image_search_proto_depIdxs = nil
}
