// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: app_image_search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageSearchService_SearchImage_FullMethodName = "/image_search.ImageSearchService/SearchImage"
	ImageSearchService_HealthCheck_FullMethodName = "/image_search.ImageSearchService/HealthCheck"
)

// ImageSearchServiceClient is the client API for ImageSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageSearchServiceClient interface {
	SearchImage(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type imageSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageSearchServiceClient(cc grpc.ClientConnInterface) ImageSearchServiceClient {
	return &imageSearchServiceClient{cc}
}

func (c *imageSearchServiceClient) SearchImage(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ImageSearchService_SearchImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageSearchServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ImageSearchService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageSearchServiceServer is the server API for ImageSearchService service.
// All implementations must embed UnimplementedImageSearchServiceServer
// for forward compatibility.
type ImageSearchServiceServer interface {
	SearchImage(context.Context, *SearchRequest) (*SearchResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedImageSearchServiceServer()
}

// UnimplementedImageSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageSearchServiceServer struct{}

func (UnimplementedImageSearchServiceServer) SearchImage(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchImage not implemented")
}
func (UnimplementedImageSearchServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedImageSearchServiceServer) mustEmbedUnimplementedImageSearchServiceServer() {}
func (UnimplementedImageSearchServiceServer) testEmbeddedByValue()                            {}

// UnsafeImageSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageSearchServiceServer will
// result in compilation errors.
type UnsafeImageSearchServiceServer interface {
	mustEmbedUnimplementedImageSearchServiceServer()
}

func RegisterImageSearchServiceServer(s grpc.ServiceRegistrar, srv ImageSearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedImageSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageSearchService_ServiceDesc, srv)
}

func _ImageSearchService_SearchImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSearchServiceServer).SearchImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSearchService_SearchImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSearchServiceServer).SearchImage(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageSearchService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSearchServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSearchService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSearchServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageSearchService_ServiceDesc is the grpc.ServiceDesc for ImageSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "image_search.ImageSearchService",
	HandlerType: (*ImageSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchImage",
			Handler:    _ImageSearchService_SearchImage_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ImageSearchService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_image_search.proto",
}
